### ISSUE TITLE
Allow for multiple Meetup Groups to be digested

### ISSUE THREAD

**Issue by lannonbr** [phacks/gatsby-source-meetup#1]
It would be useful if you could pull from multiple Meetup groups through the same endpoint. One way to do this would be possibly to allow groupUrlName to be defined as an array and then fetch the contents for each group

**Comment by phacks** [comment]
Hi @lannonbr! Starting at `v1.0.0`, you can now retrieve data from multiple Meetup Groups. You can refer to the [docs](https://github.com/phacks/gatsby-source-meetup#querying-multiple-groups) for more info.

Careful though, `v1.0.0` has a (small) breaking change, detailed in the [Changelog](https://github.com/phacks/gatsby-source-meetup/blob/master/CHANGELOG.md#breaking-changes).

Hope this helps!
